# Generated by Django 4.1.2 on 2022-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="picture_url",
            field=models.URLField(null=True),
        ),
    ]
